name: CI

on:
  workflow_dispatch:

jobs:
  wsl-container-test:
    runs-on: windows-2025

    steps:
      - name: Update WSL preview
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"

          wsl --shutdown
          wsl --update --pre-release
          wsl --shutdown

          wsl --version

      - name: Test WSLC from a fresh shell
        shell: cmd
        run: |
          wslc version

      - name: Test WSLC
        shell: pwsh
        run: |
          $process = Start-Process `
            -FilePath "cmd.exe" `
            -ArgumentList "/d", "/c", "wslc version" `
            -Wait `
            -PassThru `
            -NoNewWindow
      
          if ($process.ExitCode -ne 0) {
            throw "wslc failed with exit code $($process.ExitCode)"
          }          

      - name: Run Linux container
        shell: cmd
        run: |
          wslc run --rm alpine:latest uname -a
